version: '2'

services:
  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
      - "4444:4444"

  selenium-chrome:
    image: selenium/node-chrome
    depends_on:
      - selenium-hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  selenium-firefox:
    image: selenium/node-firefox
    depends_on:
      - selenium-hub
    environment:
     - HUB_PORT_4444_TCP_ADDR=selenium-hub
     - HUB_PORT_4444_TCP_PORT=4444
